http:
  routers:
    superinsights-staging:
      entryPoints:
        - https
      service: superinsights-staging
      rule: Host(`superinsights.coolify.intrane.fr`)
      tls:
        certresolver: letsencrypt
  services:
    superinsights-staging:
      loadBalancer:
        servers:
          -
            url: 'http://superinsights:3000'