const ACTION_CODES = {
  AUTH_REGISTER_SUCCESS: 'AUTH_REGISTER_SUCCESS',
  AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  AUTH_LOGOUT: 'AUTH_LOGOUT',

  ADMIN_INVITE_USER: 'ADMIN_INVITE_USER',

  PROJECT_CREATE: 'PROJECT_CREATE',
  PROJECT_UPDATE: 'PROJECT_UPDATE',
  PROJECT_REGENERATE_KEYS: 'PROJECT_REGENERATE_KEYS',
  PROJECT_USER_ADD: 'PROJECT_USER_ADD',
  PROJECT_USER_REMOVE: 'PROJECT_USER_REMOVE',
  PROJECT_SOFT_DELETE: 'PROJECT_SOFT_DELETE',
};

module.exports = { ACTION_CODES };
