const ACTION_CODES = {
  AUTH_REGISTER_SUCCESS: 'AUTH_REGISTER_SUCCESS',
  AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  AUTH_LOGOUT: 'AUTH_LOGOUT',

  ADMIN_INVITE_USER: 'ADMIN_INVITE_USER',

  AI_ANALYSIS_RUN_STARTED: 'AI_ANALYSIS_RUN_STARTED',
  AI_ANALYSIS_RUN_COMPLETED: 'AI_ANALYSIS_RUN_COMPLETED',
  AI_ANALYSIS_RUN_FAILED: 'AI_ANALYSIS_RUN_FAILED',

  AI_ANALYSIS_PRESET_CREATED: 'AI_ANALYSIS_PRESET_CREATED',
  AI_ANALYSIS_PRESET_UPDATED: 'AI_ANALYSIS_PRESET_UPDATED',
  AI_ANALYSIS_PRESET_DELETED: 'AI_ANALYSIS_PRESET_DELETED',
  AI_ANALYSIS_PRESET_PUBLISHED: 'AI_ANALYSIS_PRESET_PUBLISHED',
  AI_ANALYSIS_PRESET_UNPUBLISHED: 'AI_ANALYSIS_PRESET_UNPUBLISHED',
  AI_ANALYSIS_PRESET_AI_GENERATED: 'AI_ANALYSIS_PRESET_AI_GENERATED',
  AI_ANALYSIS_PRESET_AI_REFINED: 'AI_ANALYSIS_PRESET_AI_REFINED',

  PROJECT_CREATE: 'PROJECT_CREATE',
  PROJECT_UPDATE: 'PROJECT_UPDATE',
  PROJECT_REGENERATE_KEYS: 'PROJECT_REGENERATE_KEYS',
  PROJECT_PUBLIC_LINK_ENABLE: 'PROJECT_PUBLIC_LINK_ENABLE',
  PROJECT_PUBLIC_LINK_REGENERATE: 'PROJECT_PUBLIC_LINK_REGENERATE',
  PROJECT_PUBLIC_LINK_REVOKE: 'PROJECT_PUBLIC_LINK_REVOKE',
  ADMIN_PROJECT_PUBLIC_LINK_REVOKE: 'ADMIN_PROJECT_PUBLIC_LINK_REVOKE',
  PROJECT_USER_ADD: 'PROJECT_USER_ADD',
  PROJECT_USER_REMOVE: 'PROJECT_USER_REMOVE',
  PROJECT_SOFT_DELETE: 'PROJECT_SOFT_DELETE',
};

module.exports = { ACTION_CODES };
